Repository dnd-side-project/dnd-8th-8-backend, pull requests merged in 2023-02, with the labels that each got.

#33 feat: google login used spring security
  build.gradle
  docker-compose.local.yml
  docker-compose.yml
  src/main/java/com/dnd/wedding/domain/common/BaseTimeEntity.java
  src/main/java/com/dnd/wedding/domain/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/dnd/wedding/domain/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dnd/wedding/domain/jwt/JwtTokenProvider.java
  src/main/java/com/dnd/wedding/domain/jwt/RefreshToken.java
  src/main/java/com/dnd/wedding/domain/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/com/dnd/wedding/domain/jwt/repository/CookieAuthorizationRequestRepository.java
  src/main/java/com/dnd/wedding/domain/jwt/repository/RefreshTokenRedisRepository.java
  src/main/java/com/dnd/wedding/domain/member/Member.java
  src/main/java/com/dnd/wedding/domain/member/MemberRepository.java
  src/main/java/com/dnd/wedding/domain/member/Role.java
  src/main/java/com/dnd/wedding/domain/oauth/CustomUserDetails.java
  src/main/java/com/dnd/wedding/domain/oauth/OAuth2Provider.java
  src/main/java/com/dnd/wedding/domain/oauth/exception/BadRequestException.java
  src/main/java/com/dnd/wedding/domain/oauth/exception/OAuthProcessingException.java
  src/main/java/com/dnd/wedding/domain/oauth/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/dnd/wedding/domain/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/dnd/wedding/domain/oauth/info/OAuth2UserInfo.java
  src/main/java/com/dnd/wedding/domain/oauth/info/OAuth2UserInfoFactory.java
  src/main/java/com/dnd/wedding/domain/oauth/info/impl/GoogleOAuth2UserInfo.java
  src/main/java/com/dnd/wedding/domain/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/dnd/wedding/global/config/JpaConfig.java
  src/main/java/com/dnd/wedding/global/config/RedisConfig.java
  src/main/java/com/dnd/wedding/global/config/SecurityConfig.java
  src/main/java/com/dnd/wedding/global/config/util/CookieUtil.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__Add_member_table.sql
  src/test/java/com/dnd/wedding/domain/jwt/JwtAuthenticationFilterTest.java
  src/test/java/com/dnd/wedding/domain/jwt/JwtTokenProviderTest.java
  src/test/java/com/dnd/wedding/domain/jwt/handler/JwtAccessDeniedHandlerTest.java
  src/test/java/com/dnd/wedding/domain/member/MemberRepositoryTest.java
  src/test/java/com/dnd/wedding/domain/member/MemberTest.java
  src/test/java/com/dnd/wedding/domain/oauth/CustomUserDetailsTest.java
  src/test/java/com/dnd/wedding/domain/oauth/handler/OAuth2AuthenticationSuccessHandlerTest.java
  src/test/java/com/dnd/wedding/global/config/util/CookieUtilTest.java
Labels: ✨ feature, 🧪 test

#39 refactor: improve application configurations
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🛠️ refactor

#41 build: change github action workflow trigger
  .github/workflows/api-docs.yml
  .github/workflows/ci.yml
Labels: 📚 docs, 🚀 build

#42 feature: support kakao oauth login
  src/main/java/com/dnd/wedding/domain/oauth/OAuth2Provider.java
  src/main/java/com/dnd/wedding/domain/oauth/info/OAuth2UserInfoFactory.java
  src/main/java/com/dnd/wedding/domain/oauth/info/impl/KakaoOAuth2UserInfo.java
  src/main/resources/application.yml
  src/test/java/com/dnd/wedding/domain/oauth/info/OAuth2UserInfoFactoryTest.java
Labels: ✨ feature

#43 feat: renew authentication token
  src/main/java/com/dnd/wedding/domain/jwt/JwtTokenProvider.java
  src/main/java/com/dnd/wedding/domain/jwt/RefreshToken.java
  src/main/java/com/dnd/wedding/domain/jwt/controller/JwtController.java
  src/main/java/com/dnd/wedding/domain/jwt/repository/RefreshTokenRedisRepository.java
  src/main/java/com/dnd/wedding/domain/jwt/service/JwtService.java
  src/main/java/com/dnd/wedding/global/config/RedisConfig.java
  src/main/java/com/dnd/wedding/global/config/SecurityConfig.java
  src/test/java/com/dnd/wedding/domain/jwt/controller/JwtControllerTest.java
  src/test/java/com/dnd/wedding/domain/jwt/service/JwtServiceTest.java
Labels: ✨ feature

#44 refactor: reduce code smells
  src/main/java/com/dnd/wedding/domain/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dnd/wedding/domain/jwt/controller/JwtController.java
  src/main/java/com/dnd/wedding/domain/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/dnd/wedding/global/config/util/CookieUtil.java
Labels: 🛠️ refactor

#46 refactor: improve code quality
  build.gradle
  docker-compose.local.yml
  docker-compose.yml
  src/main/java/com/dnd/wedding/domain/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/dnd/wedding/domain/oauth/info/OAuth2UserInfo.java
  src/test/java/com/dnd/wedding/domain/jwt/JwtTokenProviderTest.java
  src/test/java/com/dnd/wedding/domain/jwt/service/JwtServiceTest.java
  src/test/java/com/dnd/wedding/domain/member/MemberTest.java
  src/test/java/com/dnd/wedding/domain/oauth/CustomUserDetailsTest.java
  src/test/java/com/dnd/wedding/global/config/util/CookieUtilTest.java
Labels: 🛠️ refactor

#53 feat: add common response format
  src/main/java/com/dnd/wedding/global/response/SuccessResponse.java
  src/main/resources/application.yml
  src/test/java/com/dnd/wedding/global/response/SuccessResponseTest.java
Labels: ✨ feature

#55 build: add validation dependency
  build.gradle
Labels: 🚀 build

#57 refactor: improve response class
  src/main/java/com/dnd/wedding/global/exception/ControllerExceptionHandler.java
  src/main/java/com/dnd/wedding/global/response/ErrorResponse.java
  src/main/java/com/dnd/wedding/global/response/SuccessResponse.java
  src/test/java/com/dnd/wedding/global/exception/ControllerExceptionHandlerTest.java
  src/test/java/com/dnd/wedding/global/response/SuccessResponseTest.java
Labels: 🛠️ refactor

#63 test: add custom annotation for controller test used AuthenticationPr…
  src/main/java/com/dnd/wedding/domain/member/Member.java
  src/test/java/com/dnd/wedding/global/WithMockOAuth2User.java
  src/test/java/com/dnd/wedding/global/WithMockOAuth2UserSecurityContextFactory.java
Labels: ✨ feature

#66 refactor: improve custom user details structure
  src/main/java/com/dnd/wedding/domain/jwt/JwtTokenProvider.java
  src/main/java/com/dnd/wedding/domain/oauth/CustomUserDetails.java
  src/main/java/com/dnd/wedding/domain/oauth/service/CustomOAuth2UserService.java
  src/test/java/com/dnd/wedding/domain/jwt/JwtTokenProviderTest.java
  src/test/java/com/dnd/wedding/domain/jwt/service/JwtServiceTest.java
  src/test/java/com/dnd/wedding/domain/oauth/CustomUserDetailsTest.java
  src/test/java/com/dnd/wedding/global/WithMockOAuth2UserSecurityContextFactory.java
Labels: 🛠️ refactor

#68 refactor: update success response to have custom status
  src/main/java/com/dnd/wedding/global/response/SuccessResponse.java
  src/test/java/com/dnd/wedding/global/response/SuccessResponseTest.java
Labels: 🛠️ refactor

#67 refactor: improve jwt token process
  src/docs/asciidoc/api/Authorization.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/wedding/domain/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dnd/wedding/domain/jwt/JwtTokenProvider.java
  src/main/java/com/dnd/wedding/domain/jwt/controller/JwtController.java
  src/main/java/com/dnd/wedding/domain/jwt/dto/AccessTokenResponse.java
  src/main/java/com/dnd/wedding/domain/jwt/repository/CookieAuthorizationRequestRepository.java
  src/main/java/com/dnd/wedding/domain/jwt/service/JwtService.java
  src/main/java/com/dnd/wedding/domain/oauth/CustomUserDetails.java
  src/main/java/com/dnd/wedding/domain/oauth/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/dnd/wedding/domain/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/dnd/wedding/domain/oauth/service/CustomUserDetailsService.java
  src/main/java/com/dnd/wedding/global/config/SecurityConfig.java
  src/main/java/com/dnd/wedding/global/util/CookieUtil.java
  src/main/java/com/dnd/wedding/global/util/HeaderUtil.java
  src/test/java/com/dnd/wedding/domain/jwt/JwtTokenProviderTest.java
  src/test/java/com/dnd/wedding/domain/jwt/controller/JwtControllerTest.java
  src/test/java/com/dnd/wedding/domain/oauth/CustomUserDetailsTest.java
  src/test/java/com/dnd/wedding/global/util/CookieUtilTest.java
Labels: 🛠️ refactor

#72 build: change documentation deployment trigger
  .github/workflows/api-docs.yml
Labels: 📚 docs, 🚀 build

#70 fix: resolve duplicate ducument creation
  src/test/java/com/dnd/wedding/docs/springrestdocs/AbstractRestDocsTests.java
  src/test/java/com/dnd/wedding/docs/springrestdocs/RestDocsConfiguration.java
Labels: 🐛 bug, 📚 docs, 🚀 build

#73 hotfix: allow jwt refresh api without authenticated
  src/main/java/com/dnd/wedding/global/config/SecurityConfig.java
Labels: 🐛 bug

#56 feat: user info api
  build.gradle
  src/docs/asciidoc/api/Member.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/wedding/domain/aws/service/S3Service.java
  src/main/java/com/dnd/wedding/domain/member/Gender.java
  src/main/java/com/dnd/wedding/domain/member/Member.java
  src/main/java/com/dnd/wedding/domain/member/controller/MemberController.java
  src/main/java/com/dnd/wedding/domain/member/dto/GenderDto.java
  src/main/java/com/dnd/wedding/domain/member/dto/ProfileImageDto.java
  src/main/java/com/dnd/wedding/domain/member/service/MemberService.java
  src/main/java/com/dnd/wedding/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/dnd/wedding/global/config/AwsConfig.java
  src/main/java/com/dnd/wedding/global/exception/ControllerExceptionHandler.java
  src/main/java/com/dnd/wedding/global/exception/RequestTimeoutException.java
  src/main/java/com/dnd/wedding/global/validator/EnumValidator.java
  src/main/java/com/dnd/wedding/global/validator/ValidEnum.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V1.1__Add_gender_field.sql
  src/test/java/com/dnd/wedding/domain/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/wedding/global/exception/ControllerExceptionHandlerTest.java
Labels: ✨ feature

#58 feat: checklist api
  src/docs/asciidoc/api/checklist/checklist.adoc
  src/docs/asciidoc/api/checklist/checklistItem.adoc
  src/docs/asciidoc/api/checklist/checklistSubItem.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/wedding/domain/checklist/checklistitem/ChecklistItem.java
  src/main/java/com/dnd/wedding/domain/checklist/checklistitem/controller/ChecklistItemController.java
  src/main/java/com/dnd/wedding/domain/checklist/checklistitem/dto/ChecklistItemApiDto.java
  src/main/java/com/dnd/wedding/domain/checklist/checklistitem/dto/ChecklistItemDto.java
  src/main/java/com/dnd/wedding/domain/checklist/checklistitem/repository/ChecklistItemRepository.java
  src/main/java/com/dnd/wedding/domain/checklist/checklistitem/service/ChecklistItemService.java
  src/main/java/com/dnd/wedding/domain/checklist/checklistitem/service/impl/ChecklistItemServiceImpl.java
  src/main/java/com/dnd/wedding/domain/checklist/checklistsubitem/ChecklistSubItem.java
  src/main/java/com/dnd/wedding/domain/checklist/checklistsubitem/controller/ChecklistSubItemController.java
  src/main/java/com/dnd/wedding/domain/checklist/checklistsubitem/dto/ChecklistSubItemDto.java
  src/main/java/com/dnd/wedding/domain/checklist/checklistsubitem/dto/ChecklistSubItemStateDto.java
  src/main/java/com/dnd/wedding/domain/checklist/checklistsubitem/repository/ChecklistSubItemRepository.java
  src/main/java/com/dnd/wedding/domain/checklist/checklistsubitem/service/ChecklistSubItemService.java
  src/main/java/com/dnd/wedding/domain/checklist/checklistsubitem/service/impl/ChecklistSubItemServiceImpl.java
  src/main/java/com/dnd/wedding/domain/checklist/controller/ChecklistController.java
  src/main/java/com/dnd/wedding/domain/checklist/service/ChecklistService.java
  src/main/java/com/dnd/wedding/domain/checklist/service/impl/ChecklistServiceImpl.java
  src/main/resources/db/migration/V1.2__Add_checklist_tables.sql
  src/test/java/com/dnd/wedding/domain/checklist/checklistitem/ChecklistItemTest.java
  src/test/java/com/dnd/wedding/domain/checklist/checklistitem/controller/ChecklistItemControllerTest.java
  src/test/java/com/dnd/wedding/domain/checklist/checklistitem/repository/ChecklistItemRepositoryTest.java
  src/test/java/com/dnd/wedding/domain/checklist/checklistsubitem/ChecklistSubItemTest.java
  src/test/java/com/dnd/wedding/domain/checklist/checklistsubitem/controller/ChecklistSubItemControllerTest.java
  src/test/java/com/dnd/wedding/domain/checklist/checklistsubitem/repository/ChecklistSubItemRepositoryTest.java
  src/test/java/com/dnd/wedding/domain/checklist/controller/ChecklistControllerTest.java
Labels: ✨ feature

#77 docs: update jwt api
  src/docs/asciidoc/api/Authorization.adoc
  src/test/java/com/dnd/wedding/domain/jwt/controller/JwtControllerTest.java
Labels: 📚 docs

#78 refactor: change dependency for member in checklist controller
  src/main/java/com/dnd/wedding/domain/checklist/checklistitem/controller/ChecklistItemController.java
  src/main/java/com/dnd/wedding/domain/checklist/controller/ChecklistController.java
  src/main/java/com/dnd/wedding/domain/member/service/MemberService.java
  src/main/java/com/dnd/wedding/domain/member/service/impl/MemberServiceImpl.java
  src/test/java/com/dnd/wedding/domain/checklist/checklistitem/controller/ChecklistItemControllerTest.java
  src/test/java/com/dnd/wedding/domain/checklist/checklistsubitem/controller/ChecklistSubItemControllerTest.java
  src/test/java/com/dnd/wedding/domain/checklist/controller/ChecklistControllerTest.java
Labels: ✨ feature, 🛠️ refactor

#79 docs: change access token value in member api
  src/test/java/com/dnd/wedding/domain/member/controller/MemberControllerTest.java
Labels: 📚 docs

#81 docs: update checklist api
  src/docs/asciidoc/api/checklist/checklist.adoc
  src/docs/asciidoc/api/checklist/checklistItem.adoc
  src/docs/asciidoc/api/checklist/checklistSubItem.adoc
  src/test/java/com/dnd/wedding/domain/checklist/checklistitem/controller/ChecklistItemControllerTest.java
  src/test/java/com/dnd/wedding/domain/checklist/checklistsubitem/controller/ChecklistSubItemControllerTest.java
  src/test/java/com/dnd/wedding/domain/checklist/controller/ChecklistControllerTest.java
Labels: 📚 docs

#82 docs: apply missing changes of access token value
  src/test/java/com/dnd/wedding/domain/member/controller/MemberControllerTest.java
Labels: 📚 docs

#83 chore: update project configurations
  src/main/java/com/dnd/wedding/domain/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🤔 chore

#64 bug: return unauthorized when undefined error occurs
  src/main/java/com/dnd/wedding/global/exception/ControllerExceptionHandler.java
  src/test/java/com/dnd/wedding/domain/oauth/info/OAuth2UserInfoFactoryTest.java
  src/test/java/com/dnd/wedding/global/exception/ControllerExceptionHandlerTest.java
Labels: 🐛 bug

#85 test(checklist): change time to actual value
  src/test/java/com/dnd/wedding/domain/checklist/checklistitem/controller/ChecklistItemControllerTest.java
  src/test/java/com/dnd/wedding/domain/checklist/controller/ChecklistControllerTest.java
Labels: 🧪 test

#88 feat: onboarding checklist pre check api
  src/docs/asciidoc/api/checklist/checklist.adoc
  src/main/java/com/dnd/weddingmap/domain/checklist/PreChecklistItem.java
  src/main/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistController.java
  src/main/java/com/dnd/weddingmap/domain/checklist/dto/PreChecklistItemListDto.java
  src/main/java/com/dnd/weddingmap/domain/checklist/service/ChecklistService.java
  src/main/java/com/dnd/weddingmap/domain/checklist/service/impl/ChecklistServiceImpl.java
  src/test/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistControllerTest.java
Labels: ✨ feature

#89 docs: add oauth2 login api docs
  src/docs/asciidoc/api/OAuth2.adoc
  src/docs/asciidoc/index.adoc
Labels: 📚 docs

#90 build: deploy applicaition using GitHub Actions
  .github/workflows/cd.yml
  build.gradle
  task-definition.json
Labels: 🚀 build

#93 build: optimize GitHub actions
  .github/workflows/api-docs.yml
  .github/workflows/ci.yml
Labels: 🚀 build

#95 style: change flyway migration filename format to timestamp
  src/main/resources/db/migration/V202301220121__Add_member_table.sql
  src/main/resources/db/migration/V202302092357__Add_gender_field.sql
  src/main/resources/db/migration/V202302131204__Add_checklist_tables.sql
Labels: 🛠️ refactor

#99 build: setup nginx container to ecs
  nginx/Dockerfile
  nginx/nginx.conf
  task-definition.json
Labels: 🚀 build

#100 feature: health check api
  build.gradle
  src/main/java/com/dnd/weddingmap/global/config/SecurityConfig.java
Labels: ✨ feature

#102 chore: remove docker compose for production
  docker-compose.local.yml
  docker-compose.yml
Labels: 🤔 chore

#101 refactor: improve s3 service
  src/main/java/com/dnd/weddingmap/domain/aws/service/S3Service.java
  src/main/java/com/dnd/weddingmap/domain/member/controller/MemberController.java
  src/main/java/com/dnd/weddingmap/global/service/S3Service.java
  src/test/java/com/dnd/weddingmap/domain/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/weddingmap/global/service/S3ServiceTest.java
Labels: 🛠️ refactor

#103 docs: update document page title to project name
  src/docs/asciidoc/index.adoc
Labels: 📚 docs

#104 docs: update readme to add project info
  README.md
Labels: 📚 docs

#108 build: update ecs task definition
  task-definition.json
Labels: 🚀 build

#97 feat: budget api
  src/docs/asciidoc/api/budget/transaction.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/weddingmap/domain/transaction/PaymentType.java
  src/main/java/com/dnd/weddingmap/domain/transaction/Transaction.java
  src/main/java/com/dnd/weddingmap/domain/transaction/controller/TransactionController.java
  src/main/java/com/dnd/weddingmap/domain/transaction/dto/TransactionDto.java
  src/main/java/com/dnd/weddingmap/domain/transaction/dto/TransactionListResponseDto.java
  src/main/java/com/dnd/weddingmap/domain/transaction/repository/TransactionRepository.java
  src/main/java/com/dnd/weddingmap/domain/transaction/service/TransactionService.java
  src/main/java/com/dnd/weddingmap/domain/transaction/service/impl/TransactionServiceImpl.java
  src/main/resources/db/migration/V202302212031__Create_transaction_table.sql
  src/test/java/com/dnd/weddingmap/domain/transaction/controller/TransactionControllerTest.java
Labels: ✨ feature

#111 fix: resolve out of memory on ecs container
  task-definition.json
Labels: 🚀 build, production

#112 docs: update oauth2 api docs
  src/docs/asciidoc/api/OAuth2.adoc
Labels: 📚 docs

#114 docs: modify wrong title in transaction api
  src/docs/asciidoc/api/budget/transaction.adoc
Labels: 📚 docs

#118 feat: add withdraw function to s3 service
  src/main/java/com/dnd/weddingmap/global/service/S3Service.java
Labels: ✨ feature

#122 feat: wedding api
  src/docs/asciidoc/api/wedding.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/weddingmap/domain/member/Member.java
  src/main/java/com/dnd/weddingmap/domain/wedding/Wedding.java
  src/main/java/com/dnd/weddingmap/domain/wedding/controller/WeddingController.java
  src/main/java/com/dnd/weddingmap/domain/wedding/dto/BudgetDto.java
  src/main/java/com/dnd/weddingmap/domain/wedding/dto/WeddingDayDto.java
  src/main/java/com/dnd/weddingmap/domain/wedding/repository/WeddingRepository.java
  src/main/java/com/dnd/weddingmap/domain/wedding/service/WeddingService.java
  src/main/java/com/dnd/weddingmap/domain/wedding/service/impl/WeddingServiceImpl.java
  src/main/resources/db/migration/V202302250301__Create_wedding_table.sql
  src/main/resources/db/migration/V202302281047__Rename_column_for_wedding_budget.sql
  src/test/java/com/dnd/weddingmap/domain/wedding/controller/WeddingControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/wedding/service/WeddingServiceTest.java
Labels: ✨ feature
