Repository dnd-side-project/dnd-8th-8-backend, pull requests merged in 2023-01, with the labels that each got.

#2 chore: Add templates for contribution
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#4 chore: Add idea directory to .gitignore
  .gitignore
Labels: chore

#6 feat: project initial settings
  .gitignore
  build.gradle
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/dnd/wedding/WeddingApplication.java
  src/main/resources/application.yml
  src/test/java/com/dnd/wedding/WeddingApplicationTests.java
Labels: feature

#8 build(ci): add sonarqube github actions workflow
  .github/workflows/ci.yml
Labels: build

#9 build: drop sonarcloud workflow
  .github/workflows/ci.yml
Labels: bug, build

#11 chore(docker-compose): allow all hosts to connect to the database
  docker-compose.yml
Labels: bug

#14 build: dependencies version settings
  build.gradle
Labels: build

#15 build: use checkstyle to validate code convension
  build.gradle
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
  config/checkstyle/suppressions_1_2.dtd
  src/main/java/com/dnd/wedding/WeddingApplication.java
  src/test/java/com/dnd/wedding/WeddingApplicationTests.java
Labels: build

#18 chore: add intellij java google style configuration file
  config/intellij-java-google-style.xml
Labels: chore

#20 fix: db timezone in docker-compose
  docker-compose.yml
Labels: bug

#22 chore: use spring rest docs as api docs
  .gitignore
  build.gradle
  src/docs/asciidoc/index.adoc
  src/test/java/com/dnd/wedding/docs/springrestdocs/AbstractRestDocsTests.java
  src/test/java/com/dnd/wedding/docs/springrestdocs/RestDocsConfiguration.java
Labels: chore

#23 build: integrate sonarcloud with checkstyle
  .github/workflows/ci.yml
  build.gradle
  src/test/java/com/dnd/wedding/WeddingApplicationTests.java
Labels: build

#26 build: api documentation page deployment
  .github/workflows/api-docs.yml
Labels: 📚 docs, 🚀 build

#32 build: improve spring rest docs task
  .github/workflows/api-docs.yml
  build.gradle
Labels: 🚀 build

#37 chore: set in memory db for test environment
  build.gradle
  src/test/resources/application.yml
Labels: 🤔 chore, 🧪 test, 🚀 build
