Repository dnd-side-project/dnd-8th-8-backend, pull requests merged in 2023-03, with the labels that each got.

#125 refactor: add permission check logic for checklist
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/controller/ChecklistItemController.java
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/service/ChecklistItemService.java
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/service/impl/ChecklistItemServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/controller/ChecklistSubItemController.java
  src/test/java/com/dnd/weddingmap/domain/checklist/checklistitem/controller/ChecklistItemControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/controller/ChecklistSubItemControllerTest.java
Labels: 🛠️ refactor

#129 refactor: add preparing field to wedding
  src/docs/asciidoc/api/wedding.adoc
  src/main/java/com/dnd/weddingmap/domain/wedding/Wedding.java
  src/main/java/com/dnd/weddingmap/domain/wedding/dto/WeddingDayDto.java
  src/main/java/com/dnd/weddingmap/domain/wedding/service/impl/WeddingServiceImpl.java
  src/main/resources/db/migration/V202303011627__Add_preparing_column_to_wedding.sql
  src/test/java/com/dnd/weddingmap/domain/wedding/controller/WeddingControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/wedding/service/WeddingServiceTest.java
Labels: 🛠️ refactor

#130 feature: modify username api
  src/docs/asciidoc/api/Member.adoc
  src/main/java/com/dnd/weddingmap/domain/member/Member.java
  src/main/java/com/dnd/weddingmap/domain/member/controller/MemberController.java
  src/main/java/com/dnd/weddingmap/domain/member/dto/NameDto.java
  src/main/java/com/dnd/weddingmap/domain/member/service/MemberService.java
  src/main/java/com/dnd/weddingmap/domain/member/service/impl/MemberServiceImpl.java
  src/test/java/com/dnd/weddingmap/domain/member/MemberRepositoryTest.java
  src/test/java/com/dnd/weddingmap/domain/member/MemberTest.java
  src/test/java/com/dnd/weddingmap/domain/member/controller/MemberControllerTest.java
Labels: ✨ feature

#116 chore: allow front-end domain cors
  src/main/java/com/dnd/weddingmap/global/config/SecurityConfig.java
  src/main/java/com/dnd/weddingmap/global/config/WebConfig.java
  src/main/resources/application.yml
  src/test/java/WeddingMapApplicationTest.java
  src/test/resources/application.yml
Labels: 🤔 chore

#135 build: upgrade spring boot to v3.0.3
  build.gradle
Labels: 🚀 build

#137 fix: incorrect restdocs asciidoctor version
  build.gradle
Labels: 📚 docs, 🚀 build

#140 refactor: change budget table to transaction history
  src/docs/asciidoc/api/budget/transaction.adoc
  src/test/java/com/dnd/weddingmap/domain/transaction/controller/TransactionControllerTest.java
Labels: 🛠️ refactor

#128 refactor: add permission check for transaction
  src/main/java/com/dnd/weddingmap/domain/transaction/controller/TransactionController.java
  src/main/java/com/dnd/weddingmap/domain/transaction/service/TransactionService.java
  src/main/java/com/dnd/weddingmap/domain/transaction/service/impl/TransactionServiceImpl.java
  src/test/java/com/dnd/weddingmap/domain/transaction/controller/TransactionControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/transaction/service/TransactionServiceTest.java
Labels: 🛠️ refactor

#141 test: change display name
  src/test/java/com/dnd/weddingmap/domain/contract/controller/ContractControllerTest.java
Labels: 🧪 test

#142 test: delete unnecessary csrf and accept setting
  src/test/java/com/dnd/weddingmap/domain/checklist/checklistitem/controller/ChecklistItemControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/controller/ChecklistSubItemControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/contract/controller/ContractControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/transaction/controller/TransactionControllerTest.java
Labels: 🧪 test

#143 test: change timestamp format
  src/test/java/com/dnd/weddingmap/domain/checklist/checklistitem/controller/ChecklistItemControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/contract/controller/ContractControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/transaction/controller/TransactionControllerTest.java
Labels: 🧪 test

#145 refactor: apply transactional annotation
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/service/impl/ChecklistItemServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/service/impl/ChecklistSubItemServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/checklist/service/impl/ChecklistServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/contract/service/impl/ContractServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/transaction/service/impl/TransactionServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/wedding/service/impl/WeddingServiceImpl.java
Labels: 🛠️ refactor

#146 test: add contract service test
  src/test/java/com/dnd/weddingmap/domain/contract/service/ContractServiceTest.java
Labels: 🧪 test

#150 docs: update asciidoc files
  src/docs/asciidoc/api/authorization.adoc
  src/docs/asciidoc/api/contract.adoc
  src/docs/asciidoc/api/member.adoc
  src/docs/asciidoc/api/oauth2.adoc
  src/docs/asciidoc/index.adoc
Labels: 📚 docs

#152 fix: ecs deployment fail
  task-definition.json
Labels: 🐛 bug, 🚀 build

#153 release: v1.0.0-SNAPSHOT
  build.gradle
  src/docs/asciidoc/api/authorization.adoc
  src/docs/asciidoc/api/budget/transaction.adoc
  src/docs/asciidoc/api/contract.adoc
  src/docs/asciidoc/api/member.adoc
  src/docs/asciidoc/api/oauth2.adoc
  src/docs/asciidoc/api/transaction.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/service/impl/ChecklistItemServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/service/impl/ChecklistSubItemServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/checklist/service/impl/ChecklistServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/contract/service/impl/ContractServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/transaction/controller/TransactionController.java
  src/main/java/com/dnd/weddingmap/domain/transaction/service/TransactionService.java
  src/main/java/com/dnd/weddingmap/domain/transaction/service/impl/TransactionServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/wedding/service/impl/WeddingServiceImpl.java
  src/test/java/com/dnd/weddingmap/domain/checklist/checklistitem/controller/ChecklistItemControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/controller/ChecklistSubItemControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/contract/controller/ContractControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/contract/service/ContractServiceTest.java
  src/test/java/com/dnd/weddingmap/domain/transaction/TransactionTest.java
  src/test/java/com/dnd/weddingmap/domain/transaction/controller/TransactionControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/transaction/repository/TransactionRepositoryTest.java
  src/test/java/com/dnd/weddingmap/domain/transaction/service/TransactionServiceTest.java
  task-definition.json
Labels: release

#155 feat: add get current budget api
  src/docs/asciidoc/api/budget.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/weddingmap/domain/budget/controller/BudgetController.java
  src/main/java/com/dnd/weddingmap/domain/budget/service/BudgetService.java
  src/main/java/com/dnd/weddingmap/domain/budget/service/impl/BudgetServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/transaction/repository/TransactionRepository.java
  src/test/java/com/dnd/weddingmap/domain/budget/controller/BudgetControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/budget/service/BudgetServiceTest.java
Labels: ✨ feature

#156 refactor: reorder annotations
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/ChecklistItem.java
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/controller/ChecklistItemController.java
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/service/impl/ChecklistItemServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/ChecklistSubItem.java
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/controller/ChecklistSubItemController.java
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/service/impl/ChecklistSubItemServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistController.java
  src/main/java/com/dnd/weddingmap/domain/checklist/service/impl/ChecklistServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/contract/Contract.java
  src/main/java/com/dnd/weddingmap/domain/contract/controller/ContractController.java
  src/main/java/com/dnd/weddingmap/domain/contract/dto/ContractDto.java
  src/main/java/com/dnd/weddingmap/domain/contract/dto/ContractListResponseDto.java
  src/main/java/com/dnd/weddingmap/domain/contract/service/impl/ContractServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/jwt/controller/JwtController.java
  src/main/java/com/dnd/weddingmap/domain/member/Member.java
  src/main/java/com/dnd/weddingmap/domain/member/controller/MemberController.java
  src/main/java/com/dnd/weddingmap/domain/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/dnd/weddingmap/domain/transaction/Transaction.java
  src/main/java/com/dnd/weddingmap/domain/transaction/controller/TransactionController.java
  src/main/java/com/dnd/weddingmap/domain/transaction/dto/TransactionDto.java
  src/main/java/com/dnd/weddingmap/domain/transaction/dto/TransactionListResponseDto.java
  src/main/java/com/dnd/weddingmap/domain/transaction/service/impl/TransactionServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/wedding/Wedding.java
  src/main/java/com/dnd/weddingmap/domain/wedding/controller/WeddingController.java
Labels: 🛠️ refactor

#158 release: v1.0.0-SNAPSHOT
  src/docs/asciidoc/api/budget.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/weddingmap/domain/budget/controller/BudgetController.java
  src/main/java/com/dnd/weddingmap/domain/budget/service/BudgetService.java
  src/main/java/com/dnd/weddingmap/domain/budget/service/impl/BudgetServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/ChecklistItem.java
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/controller/ChecklistItemController.java
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistitem/service/impl/ChecklistItemServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/ChecklistSubItem.java
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/controller/ChecklistSubItemController.java
  src/main/java/com/dnd/weddingmap/domain/checklist/checklistsubitem/service/impl/ChecklistSubItemServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistController.java
  src/main/java/com/dnd/weddingmap/domain/checklist/service/impl/ChecklistServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/contract/Contract.java
  src/main/java/com/dnd/weddingmap/domain/contract/controller/ContractController.java
  src/main/java/com/dnd/weddingmap/domain/contract/dto/ContractDto.java
  src/main/java/com/dnd/weddingmap/domain/contract/dto/ContractListResponseDto.java
  src/main/java/com/dnd/weddingmap/domain/contract/service/impl/ContractServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/jwt/controller/JwtController.java
  src/main/java/com/dnd/weddingmap/domain/member/Member.java
  src/main/java/com/dnd/weddingmap/domain/member/controller/MemberController.java
  src/main/java/com/dnd/weddingmap/domain/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/dnd/weddingmap/domain/transaction/Transaction.java
  src/main/java/com/dnd/weddingmap/domain/transaction/controller/TransactionController.java
  src/main/java/com/dnd/weddingmap/domain/transaction/dto/TransactionDto.java
  src/main/java/com/dnd/weddingmap/domain/transaction/dto/TransactionListResponseDto.java
  src/main/java/com/dnd/weddingmap/domain/transaction/repository/TransactionRepository.java
  src/main/java/com/dnd/weddingmap/domain/transaction/service/impl/TransactionServiceImpl.java
  src/main/java/com/dnd/weddingmap/domain/wedding/Wedding.java
  src/main/java/com/dnd/weddingmap/domain/wedding/controller/WeddingController.java
  src/main/java/com/dnd/weddingmap/global/service/S3Service.java
  src/test/java/com/dnd/weddingmap/domain/budget/controller/BudgetControllerTest.java
  src/test/java/com/dnd/weddingmap/domain/budget/service/BudgetServiceTest.java
  src/test/java/com/dnd/weddingmap/global/response/SuccessResponseTest.java
Labels: release

#162 chore: remove duplicated message.properties
  src/test/resources/messages.properties
Labels: 🤔 chore

#164 refactor: add subitem option to checklist api
  src/docs/asciidoc/api/checklist/checklist.adoc
  src/main/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistController.java
  src/main/java/com/dnd/weddingmap/domain/checklist/service/ChecklistService.java
  src/main/java/com/dnd/weddingmap/domain/checklist/service/impl/ChecklistServiceImpl.java
  src/test/java/com/dnd/weddingmap/domain/checklist/controller/ChecklistControllerTest.java
Labels: 🛠️ refactor

#165 fix(jwt): JWT String argument cannot be null or empty
  src/main/java/com/dnd/weddingmap/domain/jwt/JwtAuthenticationFilter.java
Labels: 🐛 bug
